### ISSUE TITLE
running issue for script.py 

### ISSUE THREAD

**Issue by alaa-shubbak** [tikitong/minicoco#1]
Hello 

Thank you very much for your effort and work. 
I try to use your script to have part of coco dataset. 
when I choice the number of images for the training and validation set to be 2001:667 , I got a dataset with both images and annotation .
but when I choice the num to be 3500:1500 , i got an annotation json file , without a folder of images.  

could you please help , why this is happening ?  notice that the 1st case has only two classes, while the 2nd case has 7 classes. 

another issues , the images that are uploading during running the code , is it from train2017 , or from val or test images ? 
please notice that I am trying on coco dataset. no other dataset.

**Comment by alaa-shubbak** [comment]
i try it with same ratio that you mention 30:10 
i make it 3750: 1250. but again there is no folder with images installed. 

I try to get the images from same folder of coco general images : train2017 , but it does not working correctly with my model. 

any help please?

**Comment by tikitong** [comment]
Hi @alaa-shubbak sorry for the delay, I modified the original repo with a full install step (including downloading of the annotation file). Please try and let me know if it works.

**Comment by tikitong** [comment]
@alaa-shubbak I close this issue. Feel free to re open it.
